#!/usr/bin/env bash
# Build the Carbide Motion Kiosk image.
#
# Fetches Carbide Motion, stages this repository's pi-gen stage into a pinned
# pi-gen checkout, and runs the Docker build. Output lands in deploy/.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

# shellcheck source=./build.conf
. ./build.conf

PIGEN_DIR="${PIGEN_DIR:-$REPO_ROOT/pi-gen}"
STAGE_SRC="$REPO_ROOT/stage-kiosk"

die() { printf 'build: %s\n' "$*" >&2; exit 1; }
log() { printf 'build: %s\n' "$*" >&2; }

require_docker() {
  command -v docker >/dev/null 2>&1 || die "docker is not installed"
  docker info >/dev/null 2>&1 \
    || die "the Docker daemon is not running; start Docker Desktop and retry"
}

stage_carbide_motion() {
  local deb
  export CARBIDE_MOTION_BUILD CARBIDE_MOTION_DEB_DIR
  deb="$(./scripts/fetch-carbide-motion.sh "$CARBIDE_MOTION_DEB_DIR")" \
    || die "could not obtain the Carbide Motion package"
  install -m 644 "$deb" "$STAGE_SRC/01-carbide-motion/files/carbidemotion.deb"
  log "staged $deb"
}

stage_config_template() {
  install -m 644 config/kiosk.conf.example \
    "$STAGE_SRC/07-firstboot/files/kiosk.conf.example"
}

fetch_pigen() {
  if [ ! -d "$PIGEN_DIR/.git" ]; then
    log "cloning pi-gen at $PIGEN_REF"
    git clone --quiet --branch "$PIGEN_REF" --depth 1 "$PIGEN_REPO" "$PIGEN_DIR"
  else
    git -C "$PIGEN_DIR" fetch --quiet --depth 1 origin "refs/tags/$PIGEN_REF:refs/tags/$PIGEN_REF" 2>/dev/null || true
    git -C "$PIGEN_DIR" checkout --quiet "$PIGEN_REF"
  fi
}

stage_into_pigen() {
  rm -rf "$PIGEN_DIR/stage-kiosk"
  cp -R "$STAGE_SRC" "$PIGEN_DIR/stage-kiosk"

  # Lite is the base; the desktop stages are not built at all.
  touch "$PIGEN_DIR/stage2/SKIP_IMAGES"
  local stage
  for stage in stage3 stage4 stage5; do
    [ -d "$PIGEN_DIR/$stage" ] && touch "$PIGEN_DIR/$stage/SKIP"
  done
}

write_pigen_config() {
  cat > "$PIGEN_DIR/config" <<CFG
# Generated by build.sh from build.conf. Edit build.conf, not this file.
IMG_NAME='$IMG_NAME'
TARGET_HOSTNAME='$TARGET_HOSTNAME'
DEPLOY_COMPRESSION='$DEPLOY_COMPRESSION'
LOCALE_DEFAULT='$LOCALE_DEFAULT'
KEYBOARD_LAYOUT='$KEYBOARD_LAYOUT'
TIMEZONE_DEFAULT='$TIMEZONE_DEFAULT'
STAGE_LIST='stage0 stage1 stage2 stage-kiosk'

# The kiosk account is created by the stage; pi-gen's own first user is not
# used and SSH stays off unless kiosk.conf turns it on.
FIRST_USER_NAME='kiosk'
DISABLE_FIRST_BOOT_USER_RENAME=1
ENABLE_SSH=0
CFG
}

collect_output() {
  install -d "$REPO_ROOT/deploy"
  if compgen -G "$PIGEN_DIR/deploy/*" >/dev/null; then
    cp -f "$PIGEN_DIR"/deploy/* "$REPO_ROOT/deploy/"
    ( cd "$REPO_ROOT/deploy" && ls -1 )
  else
    die "pi-gen produced no output in $PIGEN_DIR/deploy"
  fi
}

main() {
  require_docker
  stage_carbide_motion
  stage_config_template
  fetch_pigen
  stage_into_pigen
  write_pigen_config
  log "starting pi-gen build (this takes a while)"
  ( cd "$PIGEN_DIR" && ./build-docker.sh )
  collect_output
  log "done"
}

main "$@"
