#!/usr/bin/env bash
# Build the Carbide Motion Kiosk image.
#
# Fetches Carbide Motion, stages this repository's pi-gen stage into a pinned
# pi-gen checkout, and runs the Docker build. Output lands in deploy/.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

# shellcheck source=./build.conf
. ./build.conf

PIGEN_DIR="${PIGEN_DIR:-$REPO_ROOT/pi-gen}"
STAGE_SRC="$REPO_ROOT/stage-kiosk"

die() { printf 'build: %s\n' "$*" >&2; exit 1; }
log() { printf 'build: %s\n' "$*" >&2; }

require_docker() {
  command -v docker >/dev/null 2>&1 || die "docker is not installed"
  docker info >/dev/null 2>&1 \
    || die "the Docker daemon is not running; start Docker Desktop and retry"
}

stage_carbide_motion() {
  local deb
  export CARBIDE_MOTION_BUILD CARBIDE_MOTION_DEB_DIR
  deb="$(./scripts/fetch-carbide-motion.sh "$CARBIDE_MOTION_DEB_DIR")" \
    || die "could not obtain the Carbide Motion package"
  # git does not track empty directories, so a clean clone has no files/ here.
  install -d "$STAGE_SRC/01-carbide-motion/files"
  install -m 644 "$deb" "$STAGE_SRC/01-carbide-motion/files/carbidemotion.deb"
  log "staged $deb"
}

stage_config_template() {
  install -d "$STAGE_SRC/07-firstboot/files"
  install -m 644 config/kiosk.conf.example \
    "$STAGE_SRC/07-firstboot/files/kiosk.conf.example"
}

fetch_pigen() {
  if [ ! -d "$PIGEN_DIR/.git" ]; then
    log "cloning pi-gen at $PIGEN_REF"
    git clone --quiet --branch "$PIGEN_REF" --depth 1 "$PIGEN_REPO" "$PIGEN_DIR"
  else
    git -C "$PIGEN_DIR" fetch --quiet --depth 1 origin "refs/tags/$PIGEN_REF:refs/tags/$PIGEN_REF" 2>/dev/null || true
    git -C "$PIGEN_DIR" checkout --quiet "$PIGEN_REF"
  fi
}

# pi-gen assumes a Linux host. On an Apple Silicon Mac two of its assumptions
# are wrong at once, and the second is only reachable after the first.
#
# It picks its build container's base image from `uname -m`. macOS reports
# arm64 where Linux reports aarch64, so pi-gen misses its own 64-bit case and
# lands on a native 64-bit Debian instead of a 32-bit one. Then scripts/common
# runs the debootstrap and every chroot under `setarch linux32`, which fails:
# Docker Desktop's linuxkit kernel has no AArch32 support, and Apple Silicon
# cannot execute 32-bit ARM natively at all. The bootstrap is invoked with
# `|| true`, so that failure is swallowed and only surfaces one stage later as
# an empty rootfs - which is what "cannot create stage0/rootfs/etc/apt/" is.
#
# An armhf base image is already 32-bit and runs under emulation, so the
# personality change is both unavailable and unnecessary. Set one, and drop
# the setarch calls that would otherwise fail inside it.
patch_pigen_for_apple_silicon() {
  [ "$(uname -s)" = "Darwin" ] || return 0
  case "$(uname -m)" in arm64|aarch64) ;; *) return 0 ;; esac

  # A 32-bit ARM build container, which pi-gen's own arch detection cannot
  # reach from macOS.
  sed -i.orig -E 's@^( *)BASE_IMAGE=debian:bookworm$@\1BASE_IMAGE=arm32v7/debian:bookworm@' \
    "$PIGEN_DIR/build-docker.sh"
  grep -q 'BASE_IMAGE=arm32v7/debian:bookworm' "$PIGEN_DIR/build-docker.sh" \
    || die "could not point pi-gen at a 32-bit base image"

  # Already 32-bit, so these only fail. Removing the prefix leaves capsh to
  # run exactly as it would have.
  sed -i.orig 's@setarch linux32 capsh@capsh@g' "$PIGEN_DIR/scripts/common"
  ! grep -q 'setarch linux32' "$PIGEN_DIR/scripts/common" \
    || die "could not remove the setarch calls from pi-gen"

  log "patched pi-gen for an Apple Silicon host"
}

stage_into_pigen() {
  rm -rf "$PIGEN_DIR/stage-kiosk"
  cp -R "$STAGE_SRC" "$PIGEN_DIR/stage-kiosk"

  # Lite is the base; the desktop stages are not built at all.
  touch "$PIGEN_DIR/stage2/SKIP_IMAGES"
  local stage
  for stage in stage3 stage4 stage5; do
    [ -d "$PIGEN_DIR/$stage" ] && touch "$PIGEN_DIR/$stage/SKIP"
  done
}

write_pigen_config() {
  # pi-gen insists on a first-user password whenever the first-boot rename
  # wizard is disabled, and disabling that wizard is what makes the image
  # headless. The kiosk stage locks the account immediately afterwards, so
  # this value is never usable for login; generating it per build means no
  # published image ever carries a known credential.
  local first_user_pass
  first_user_pass="$(od -An -tx1 -N24 /dev/urandom | tr -d ' \n')"
  [ "${#first_user_pass}" -ge 32 ] || die "could not generate a first-user password"

  cat > "$PIGEN_DIR/config" <<CFG
# Generated by build.sh from build.conf. Edit build.conf, not this file.
IMG_NAME='$IMG_NAME'
TARGET_HOSTNAME='$TARGET_HOSTNAME'
DEPLOY_COMPRESSION='$DEPLOY_COMPRESSION'
LOCALE_DEFAULT='$LOCALE_DEFAULT'
KEYBOARD_LAYOUT='$KEYBOARD_LAYOUT'
TIMEZONE_DEFAULT='$TIMEZONE_DEFAULT'
STAGE_LIST='stage0 stage1 stage2 stage-kiosk'

# The kiosk account is created by the stage; pi-gen's own first user is not
# used and SSH stays off unless kiosk.conf turns it on.
FIRST_USER_NAME='kiosk'
FIRST_USER_PASS='$first_user_pass'
DISABLE_FIRST_BOOT_USER_RENAME=1
ENABLE_SSH=0
CFG
}

collect_output() {
  install -d "$REPO_ROOT/deploy"
  if compgen -G "$PIGEN_DIR/deploy/*" >/dev/null; then
    cp -f "$PIGEN_DIR"/deploy/* "$REPO_ROOT/deploy/"
    ( cd "$REPO_ROOT/deploy" && ls -1 )
  else
    die "pi-gen produced no output in $PIGEN_DIR/deploy"
  fi
}

main() {
  # Staging touches no containers, so it stays runnable without a daemon.
  [ "${CARBIDE_STAGE_ONLY:-0}" = "1" ] || require_docker
  stage_carbide_motion
  stage_config_template
  fetch_pigen
  patch_pigen_for_apple_silicon
  stage_into_pigen
  write_pigen_config
  if [ "${CARBIDE_STAGE_ONLY:-0}" = "1" ]; then
    log "staging complete; CARBIDE_STAGE_ONLY is set, not building"
    return 0
  fi
  log "starting pi-gen build (this takes a while)"
  ( cd "$PIGEN_DIR" && ./build-docker.sh )
  collect_output
  log "done"
}

main "$@"
